spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: false
jwt:
  secret: ${JWT_SECRET}
  expiratio: ${JWT_EXPIRATION}